name: ESLint Check

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Node Install
        run: npm ci

      - uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: "--ignore-path=.gitignore --quiet"
          extensions: "ts"
          annotations: true
