name: Run Tests

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Node Install
        run: npm ci

      - name: Test
        run: npm test